/***********************************************************
 * Software: instrument gui library
 * Module:   Testing root suite class
 * Version:  0.1
 * Licence:  GPL2
 *
 * Owner: Kim Kristo
 * Date creation : 4.9.2012
 *
 ***********************************************************/


import junit.framework.*;


public class RootSuite extends TestCase {
    
    public RootSuite(String testName) {
        super(testName);
    }

    @Override
    protected void setUp() throws java.lang.Exception {
    }

    @Override
    protected void tearDown() throws java.lang.Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    

    /**
     * suite method automatically generated by JUnit module
     * @return 
     */
    public static junit.framework.Test suite() {
        junit.framework.TestSuite suite = new junit.framework.TestSuite("RootSuite");
        return suite;
    }
    
    // TODO add test methods here. The name must begin with 'test'. For example:
    // public void testHello() {}
    
}
