
/***********************************************************
 * Software: instrument gui library
 * Module:   Test case for ScopePlot class
 * Version:  0.1
 * Licence:  GPL2
 *
 * Owner: Kim Kristo
 * Date creation : 4.9.2012
 *
 ***********************************************************/
import oh3ebf.lib.gui.ScopePlot;

public class TestScopeObject extends javax.swing.JFrame {

    /** Creates new form TestDrawingObject */
    public TestScopeObject() {
        ScopePlot p = new ScopePlot(2, null);

        this.add(p);
        initComponents();
    }

    public boolean exit() {
        return (true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TestWindow");
        setLocationByPlatform(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TestScopeObject().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
