/***********************************************************
 * Software: instrument gui library
 * Module:   smith chart drawing class
 * Version:  0.1
 * Licence:  GPL2
 *
 * Owner: Kim Kristo
 * Date creation : 22.12.2012
 *
 ***********************************************************/
package oh3ebf.lib.gui;

import oh3ebf.lib.gui.primitives.SmithChartGrid;
import oh3ebf.lib.gui.primitives.SmithPoint;

public class SmithChartPlot extends Plot {

    private SmithChartGrid sGrid;

    /** Creates a new instance of SmithChart */
    public SmithChartPlot() {
        // init some data structures
        super();

        sGrid = new SmithChartGrid();
        add(sGrid);

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(160, 400));
        setMinimumSize(new java.awt.Dimension(160, 400));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        double scale = sGrid.getScale();
        double offset_x = sGrid.getOffsetX();
        double offset_y = sGrid.getOffsetY();

        int clickx = (evt.getX() - (int) Math.round(scale + offset_x));
        int clicky = (evt.getY() - (int) Math.round(scale + offset_y));

        SmithPoint s = new SmithPoint("", 1.0, 1.0, 1.0, true);
        //s.invertPoint();
        
        //s.getPosition();
        s.setPointByXY(clickx/scale, clicky/scale);



        //System.out.println("x: " + clickx + " y: " + -clicky);
    }//GEN-LAST:event_formMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
